### ISSUE TITLE
Simple question - how to test this extension? :)

### ISSUE THREAD

**Issue by timothywarner** [copilot-extensions/github-models-extension#12]
Hey team! Would you please expand the instructions just a teeny bit? I'm probably missing something simple, but I have no idea how to go from running the Node project on my Win 11 workstation to sending requests to @models in VS Code. 

I do have the latest release builds of VS Code and the GitHub Copilot completion & chat extensions. I am in the beta program and can successfully chat with other GitHub Copilot extensions like Docker & README API.

Thanks again!
Tim

**Comment by Houndie** [comment]
Hi @timothywarner !  README has been updated with docs.
